In [1]:
import numpy as np

In [3]:
np.__version__

'2.1.3'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
print(type(arr)) #nd means multidimensional

<class 'numpy.ndarray'>


In [ ]:
# in list we can store multiple datatyes 

## arange

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.arange(20,10) # 1st arg is always less than 2nd arg

array([], dtype=int64)

In [15]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

## zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros(5,dtype=int)  # hyperparameter tuningdtype=float  1d array

array([0, 0, 0, 0, 0])

In [21]:
np.zeros([5,4])  #nd arrray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros([10,10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## ones

In [23]:
np.ones(2)

array([1., 1.])

In [24]:
np.ones(2,dtype = int)

array([1, 1])

In [25]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [26]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr

array([0, 1, 2, 3, 4, 5])

## random

In [28]:
rand(3,2)

NameError: name 'rand' is not defined

In [29]:
np.random.rand(3,2)

array([[0.60072874, 0.63528183],
       [0.90967228, 0.11323451],
       [0.29876414, 0.87553764]])

In [30]:
np.random.rand(3,2)

array([[0.71331067, 0.51800986],
       [0.03549071, 0.17991005],
       [0.40214139, 0.4874373 ]])

In [31]:
np.random.rand(3,2)

array([[0.21957654, 0.02044881],
       [0.53934978, 0.86383317],
       [0.85758542, 0.11553317]])

In [32]:
np.random.rand(3)

array([0.69239488, 0.26360579, 0.49440015])

In [33]:
np.random.randint(4,6)

4

In [36]:
np.random.randint(0,10)

7

In [39]:
np.random.randint(0,10,5)

array([4, 3, 5, 2, 1], dtype=int32)

In [42]:
n= np.random.randint(10,40,(8,10))
n

array([[31, 11, 12, 38, 20, 27, 37, 31, 18, 16],
       [17, 32, 16, 36, 10, 29, 39, 10, 39, 18],
       [29, 15, 26, 26, 25, 22, 21, 38, 27, 26],
       [28, 38, 25, 35, 39, 20, 11, 20, 11, 37],
       [28, 25, 16, 39, 39, 20, 28, 20, 20, 33],
       [29, 27, 19, 36, 15, 28, 21, 32, 36, 28],
       [23, 11, 27, 28, 12, 21, 14, 12, 34, 19],
       [11, 15, 15, 18, 13, 21, 20, 36, 23, 32]], dtype=int32)

In [43]:
n= np.random.randint(10,40,(10,10))
n

array([[38, 14, 32, 18, 15, 32, 30, 21, 12, 15],
       [23, 26, 19, 12, 36, 25, 16, 22, 26, 20],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [33, 10, 36, 24, 28, 30, 18, 31, 23, 33],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [26, 12, 28, 36, 32, 29, 21, 22, 23, 28],
       [26, 29, 31, 27, 24, 31, 21, 34, 19, 22],
       [33, 33, 39, 24, 11, 16, 22, 15, 25, 23],
       [39, 19, 24, 39, 24, 35, 22, 13, 25, 35],
       [38, 33, 25, 29, 38, 12, 14, 19, 30, 20]], dtype=int32)

In [44]:
n[0]

array([38, 14, 32, 18, 15, 32, 30, 21, 12, 15], dtype=int32)

In [45]:
n[6]

array([26, 29, 31, 27, 24, 31, 21, 34, 19, 22], dtype=int32)

In [46]:
n[0:6]

array([[38, 14, 32, 18, 15, 32, 30, 21, 12, 15],
       [23, 26, 19, 12, 36, 25, 16, 22, 26, 20],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [33, 10, 36, 24, 28, 30, 18, 31, 23, 33],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [26, 12, 28, 36, 32, 29, 21, 22, 23, 28]], dtype=int32)

In [47]:
n[::-1]

array([[38, 33, 25, 29, 38, 12, 14, 19, 30, 20],
       [39, 19, 24, 39, 24, 35, 22, 13, 25, 35],
       [33, 33, 39, 24, 11, 16, 22, 15, 25, 23],
       [26, 29, 31, 27, 24, 31, 21, 34, 19, 22],
       [26, 12, 28, 36, 32, 29, 21, 22, 23, 28],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [33, 10, 36, 24, 28, 30, 18, 31, 23, 33],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [23, 26, 19, 12, 36, 25, 16, 22, 26, 20],
       [38, 14, 32, 18, 15, 32, 30, 21, 12, 15]], dtype=int32)

In [48]:
n[::1]

array([[38, 14, 32, 18, 15, 32, 30, 21, 12, 15],
       [23, 26, 19, 12, 36, 25, 16, 22, 26, 20],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [33, 10, 36, 24, 28, 30, 18, 31, 23, 33],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [26, 12, 28, 36, 32, 29, 21, 22, 23, 28],
       [26, 29, 31, 27, 24, 31, 21, 34, 19, 22],
       [33, 33, 39, 24, 11, 16, 22, 15, 25, 23],
       [39, 19, 24, 39, 24, 35, 22, 13, 25, 35],
       [38, 33, 25, 29, 38, 12, 14, 19, 30, 20]], dtype=int32)

In [49]:
n[::2]

array([[38, 14, 32, 18, 15, 32, 30, 21, 12, 15],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [26, 29, 31, 27, 24, 31, 21, 34, 19, 22],
       [39, 19, 24, 39, 24, 35, 22, 13, 25, 35]], dtype=int32)

In [50]:
n

array([[38, 14, 32, 18, 15, 32, 30, 21, 12, 15],
       [23, 26, 19, 12, 36, 25, 16, 22, 26, 20],
       [19, 38, 21, 37, 38, 31, 18, 12, 29, 21],
       [33, 10, 36, 24, 28, 30, 18, 31, 23, 33],
       [28, 16, 30, 26, 17, 32, 25, 36, 21, 11],
       [26, 12, 28, 36, 32, 29, 21, 22, 23, 28],
       [26, 29, 31, 27, 24, 31, 21, 34, 19, 22],
       [33, 33, 39, 24, 11, 16, 22, 15, 25, 23],
       [39, 19, 24, 39, 24, 35, 22, 13, 25, 35],
       [38, 33, 25, 29, 38, 12, 14, 19, 30, 20]], dtype=int32)

In [51]:
n[0,5]

np.int32(32)

In [52]:
n[5,-3]

np.int32(22)

In [53]:
x = n[5,-3]
print(x)

22


In [54]:
np.arange(1,13).reshape(3,4) #

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [56]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [57]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [61]:
np.arange(1,13).reshape(1,5)

ValueError: cannot reshape array of size 12 into shape (1,5)